// Biography and abstracts retain their source wording; publication rights are recorded per paper.
const siteContent = {
  "intro": "Hi! I am currently a PhD student in the <a href=\"https://ece.illinois.edu/\">Electrical and Computer Engineering department</a> at the University of Illinois Urbana Champaign. I am guided by <a href=\"https://www.varshney.csl.illinois.edu/\">Prof. Lav Varshney</a>.",
  "biography": "<p>Hi! I am currently a PhD student in the <a href=\"https://ece.illinois.edu/\">Electrical and Computer Engineering department</a> at the University of Illinois Urbana Champaign. I am guided by <a href=\"https://www.varshney.csl.illinois.edu/\">Prof. Lav Varshney</a>. Previously I have worked at <a href=\"https://www.amd.com/en\">AMD</a> as a Silicon Design Engineer. I completed my B.Tech (Hons) and M.Tech degrees from the <a href=\"http://www.ee.iitm.ac.in/\">Electrical Engineering department</a> at Indian Institute of Technology Madras. I did my Master's thesis under the guidance of <a href=\"https://people.epfl.ch/andreas.burg/?lang=en\">Prof. Andreas Burg</a> at EPFL. During my time at IIT Madras, I also worked under <a href=\"http://www.ee.iitm.ac.in/janakiraman/\">Prof. Janakiraman Viraraghavan</a> and <a href=\"http://www.ee.iitm.ac.in/~raju/\">Prof. A.N. Rajagopalan</a> as a research assistant.</p>\n<p>My academic interests lie at the interface of VLSI, Signal Processing and Machine Learning. This webpage consists of activities that have influenced my affinity towards these fields.</p>",
  "personal": "<p>I am someone who is very energetic and passionate about things I like. I am a former National level Badminton player and currently represent my institute UIUC at various sports meets. I am an ardent sports fan and watch a broad spectrum of sports: Tennis, Football, Formula 1, Cricket, and Basketball, to name a few.</p>\n<p>Rafael Nadal is one of my sporting idols; his passion and never-give-up attitude is something I try to incorporate in my daily life. Apart from him, I am also moved by the greatness and qualities of Lionel Messi, Sebastian Vettel, and Virat Kohli. Among the many things, I admire their ability to stay humble despite the fame and recognition amassed by them. I believe that sports can shape a person by giving them everlasting memories.</p>\n<p>I also pursue drawing and pencil sketching as a hobby. In my free time, I read novels of fiction and myth genre.</p>",
  "teaching": "<p>I enjoy being a Teaching Assistant, explaining concepts, and clarifying doubts of other students. This helps me interpret the subject from different perspectives.</p>\n<div class=\"teaching-course\"><p><strong>Course:</strong> Adaptive Signal Processing (EE6110)</p><p><strong>Role:</strong> Teaching Assistant (Fall 2020)</p><p><strong>Instructor:</strong> Prof. Srikrishna Bhashyam, IIT Madras</p><p><a href=\"https://www.ee.iitm.ac.in/~skrishna/ee6110/\"><strong>Course webpage</strong> ↗</a></p></div>\n<div class=\"teaching-course\"><p><strong>Course:</strong> Digital IC Design (EE5311)</p><p><strong>Role:</strong> Teaching Assistant (Fall 2020)</p><p><strong>Instructor:</strong> Prof. Janakiraman Viraraghavan, IIT Madras</p><p><a href=\"http://www.ee.iitm.ac.in/vlsi/courses/ee5311_2020\"><strong>Course webpage</strong> ↗</a></p></div>\n<div class=\"teaching-course\"><p><strong>Course:</strong> Image Signal Processing (EE5175)</p><p><strong>Role:</strong> Teaching Assistant (Spring 2021)</p><p><strong>Instructor:</strong> Prof. A. N. Rajagopalan, IIT Madras</p><p><a href=\"http://www.ee.iitm.ac.in/2015/03/image-signal-processing-ee5175/\"><strong>Course webpage</strong> ↗</a></p></div>\n<div class=\"teaching-course\"><p><strong>Course:</strong> VLSI in Machine Learning (ECE498)</p><p><strong>Role:</strong> Teaching Assistant (Fall 2024)</p><p><strong>Instructor:</strong> Prof. Naresh R. Shanbhag, UIUC</p><p><a href=\"https://courses.grainger.illinois.edu/ECE498NSG/fa2024/\"><strong>Course webpage</strong> ↗</a></p></div>\n<div class=\"teaching-course\"><p><strong>Course:</strong> Introduction to Optimization (ECE490)</p><p><strong>Role:</strong> Teaching Assistant (Spring 2025)</p><p><strong>Instructor:</strong> Prof. Max Raginsky, UIUC</p><p><a href=\"https://maxim.ece.illinois.edu/teaching/spring25/\"><strong>Course webpage</strong> ↗</a></p></div>",
  "papers": [
    {
      "title": "Verifier-Threshold: An Efficient Test-Time Scaling Approach for Image Generation",
      "url": "https://openreview.net/pdf?id=kEQ3GODGYt",
      "authors": "<strong>Vignesh Sundaresha</strong>, Akash Haridas, Vikram Appia, Lav R. Varshney",
      "venue": "International Conference on Learning Representations (ICLR) Workshop on Real-World Constrained and Preference-Aligned Flow and Diffusion-Based Models 2026",
      "year": 2026,
      "tags": [
        "ml"
      ],
      "abstract": "Image generation has emerged as a mainstream application of large generative models. Just as test-time compute and reasoning have improved language model capabilities, similar benefits have been observed for image generation models. In particular, searching over noise samples for diffusion and flow models has been shown to scale well with test-time compute. While recent works explore allocating non-uniform inference-compute budgets across denoising steps, existing approaches rely on greedy heuristics and often allocate the compute budget ineffectively. In this work, we study this problem and propose a simple fix. We propose Verifier-Threshold, which automatically reallocates test-time compute and delivers substantial efficiency improvements. For the same performance on the GenEval benchmark, we achieve a 2-4x reduction in computational time over the state-of-the-art method.",
      "abstractSource": "https://arxiv.org/abs/2512.08985v3",
      "citationChicago": "Sundaresha, Vignesh, Akash Haridas, Vikram Appia, and Lav R. Varshney. “Verifier-Threshold: An Efficient Test-Time Scaling Approach for Image Generation.” Paper presented at the ICLR Workshop on Real-World Constrained and Preference-Aligned Flow and Diffusion-Based Models, 2026. <a href=\"https://openreview.net/pdf?id=kEQ3GODGYt\">https://openreview.net/pdf?id=kEQ3GODGYt</a>.",
      "type": "workshop",
      "bibtex": "@inproceedings{sundaresha2026verifier,\n  title = {{Verifier-Threshold: An Efficient Test-Time Scaling Approach for Image Generation}},\n  author = {Vignesh Sundaresha and Akash Haridas and Vikram Appia and Lav R. Varshney},\n  year = {2026},\n  booktitle = {International Conference on Learning Representations (ICLR) Workshop on Real-World Constrained and Preference-Aligned Flow and Diffusion-Based Models 2026},\n  url = {https://openreview.net/pdf?id=kEQ3GODGYt}\n}",
      "rightsNotice": "Abstract reproduced from the linked arXiv version under <a href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/\">CC BY-NC-ND 4.0</a>. Wording unchanged."
    },
    {
      "title": "A 28nm 31.2 TOPS/W Diffusion Transformer Accelerator Using Memory-in-Compute Architecture",
      "url": "https://doi.org/10.1109/ESSERC66193.2025.11214030",
      "authors": "Soonha Hwang, Kaining Zhou, Nathan Chiang, <strong>Vignesh Sundaresha</strong>, Naresh Shanbhag",
      "venue": "2025 IEEE European Solid-State Electronics Research Conference (ESSERC)",
      "year": 2025,
      "tags": [
        "vlsi"
      ],
      "abstract": "Diffusion transformers (DiTs) are effective for image and video generation, but their large model sizes and high computational requirements hinder their use on resource-constrained platforms. To address these major challenges, this work presents a DiT accelerator which enables efficient deployment on edge devices. The accelerator is co-designed with a state-of-the-art (SOTA) 2.2 M parameter count DiT algorithm achieving a Fréchet Inception Distance (FID) of 10.9. The accelerator adopts a custom instruction-set architecture (ISA) with an optimized vectorized processing execution model. A digital in-memory computing (DIMC) architecture is employed to speed-up the compute-heavy matrix-vector multiply (MVM) kernels in the DiT algorithm. A novel DIMC floorplan called memory-in-compute architecture (MICA) is proposed to alleviate the energy and latency overhead of DIMC’s digital summer. MICA is further employed to efficiently generate independent Gaussian noise samples on-chip to support DiT’s generative functionality. Measured results from a prototype IC fabricated in a 28 nm process indicates the MICA macro operates at a maximum frequency of 525 MHz, achieves a SOTA compute density of 1.52 TOPS/mm² at (1 V, 525 MHz) and a SOTA energy efficiency of 31.2 TOPS/W at (0.52 V, 100 MHz).",
      "abstractSource": "https://www.esserc2025.org/_files/ugd/aa54ce_cba8f3ef666b4cf1906fc7862a8c6e6a.pdf",
      "citationChicago": "Hwang, Soonha, Kaining Zhou, Nathan Chiang, Vignesh Sundaresha, and Naresh Shanbhag. “A 28nm 31.2 TOPS/W Diffusion Transformer Accelerator Using Memory-in-Compute Architecture.” In <em>Proceedings of the 2025 IEEE European Solid-State Electronics Research Conference (ESSERC)</em>, 437–40. IEEE, 2025. <a href=\"https://doi.org/10.1109/ESSERC66193.2025.11214030\">https://doi.org/10.1109/ESSERC66193.2025.11214030</a>.",
      "type": "conference",
      "bibtex": "@inproceedings{hwang2025diffusion,\n  title = {{A 28nm 31.2 TOPS/W Diffusion Transformer Accelerator Using Memory-in-Compute Architecture}},\n  author = {Soonha Hwang and Kaining Zhou and Nathan Chiang and Vignesh Sundaresha and Naresh Shanbhag},\n  year = {2025},\n  booktitle = {2025 IEEE European Solid-State Electronics Research Conference (ESSERC)},\n  pages = {437--440},\n  doi = {10.1109/ESSERC66193.2025.11214030},\n  url = {https://doi.org/10.1109/ESSERC66193.2025.11214030}\n}",
      "rightsNotice": "© 2025 IEEE. Personal use of this material is permitted. Permission from IEEE must be obtained for all other uses, in any current or future media, including reprinting/republishing this material for advertising or promotional purposes, creating new collective works, for resale or redistribution to servers or lists, or reuse of any copyrighted component of this work in other works."
    },
    {
      "title": "Designing Parameter and Compute Efficient Diffusion Transformers using Distillation",
      "url": "https://openreview.net/pdf?id=x1xp9gmszo",
      "authors": "<strong>Vignesh Sundaresha</strong>",
      "venue": "International Conference on Learning Representations (ICLR) Workshop on Deep Generative Models in Machine Learning 2025",
      "year": 2025,
      "tags": [
        "ml"
      ],
      "abstract": "Diffusion Transformers (DiTs) with billions of model parameters form the backbone of popular image and video generation models like DALL.E, Stable-Diffusion and SORA. Though these models are necessary in many low-latency applications like Augmented/Virtual Reality, they cannot be deployed on resource-constrained Edge devices (like Apple Vision Pro or Meta Ray-Ban glasses) due to their huge computational complexity. To overcome this, we turn to knowledge distillation and perform a thorough design-space exploration to achieve the best DiT for a given parameter size. In particular, we provide principles for how to choose design knobs such as depth, width, attention heads and distillation setup for a DiT. During the process, a three-way trade-off emerges between model performance, size and speed that is crucial for Edge implementation of diffusion. We also propose two distillation approaches - Teaching Assistant (TA) method and Multi-In-One (MI1) method - to perform feature distillation in the DiT context. Unlike existing solutions, we demonstrate and benchmark the efficacy of our approaches on practical Edge devices such as NVIDIA Jetson Orin Nano.",
      "abstractSource": "https://arxiv.org/abs/2502.14226v1",
      "citationChicago": "Sundaresha, Vignesh. “Designing Parameter and Compute Efficient Diffusion Transformers Using Distillation.” Paper presented at the ICLR Workshop on Deep Generative Models in Machine Learning, 2025. <a href=\"https://openreview.net/pdf?id=x1xp9gmszo\">https://openreview.net/pdf?id=x1xp9gmszo</a>.",
      "type": "workshop",
      "bibtex": "@inproceedings{sundaresha2025distillation,\n  title = {{Designing Parameter and Compute Efficient Diffusion Transformers using Distillation}},\n  author = {Vignesh Sundaresha},\n  year = {2025},\n  booktitle = {International Conference on Learning Representations (ICLR) Workshop on Deep Generative Models in Machine Learning 2025},\n  url = {https://openreview.net/pdf?id=x1xp9gmszo}\n}",
      "rightsNotice": "Abstract reproduced from the linked arXiv version under <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0</a>. Wording unchanged."
    },
    {
      "title": "Grow to Compress? Efficient Training of Robust Networks on the Edge",
      "url": "https://openreview.net/pdf?id=8rko2UqXdB",
      "authors": "<strong>Vignesh Sundaresha</strong>, Naresh Shanbhag",
      "venue": "Neural Information Processing Systems (NeurIPS) Workshop on Machine Learning and Compression 2024",
      "year": 2024,
      "tags": [
        "ml"
      ],
      "abstract": "The ubiquitous deployment of deep learning systems on resource-constrained Edge devices is hindered by their high computational complexity coupled with their fragility to out-of-distribution (OOD) data, especially to naturally occurring common corruptions. Current solutions rely on the Cloud to train and compress models before deploying to the Edge. This incurs high energy and latency costs in transmitting locally acquired field data to the Cloud while also raising privacy concerns. We propose GEARnn (Growing Efficient, Accurate, and Robust neural networks) to grow and train robust networks in-situ, i.e., completely on the Edge device. Starting with a low-complexity initial backbone network, GEARnn employs One-Shot Growth (OSG) to grow a network satisfying the memory constraints of the Edge device using clean data, and robustifies the network using Efficient Robust Augmentation (ERA) to obtain the final network. We demonstrate results on a NVIDIA Jetson Xavier NX, and analyze the trade-offs between accuracy, robustness, model size, energy consumption, and training time. Our results demonstrate the construction of efficient, accurate, and robust networks entirely on an Edge device.",
      "abstractSource": "https://arxiv.org/abs/2410.07691v1",
      "citationChicago": "Sundaresha, Vignesh, and Naresh Shanbhag. “Grow to Compress? Efficient Training of Robust Networks on the Edge.” Paper presented at the NeurIPS Workshop on Machine Learning and Compression, 2024. <a href=\"https://openreview.net/pdf?id=8rko2UqXdB\">https://openreview.net/pdf?id=8rko2UqXdB</a>.",
      "type": "workshop",
      "bibtex": "@inproceedings{sundaresha2024grow,\n  title = {{Grow to Compress? Efficient Training of Robust Networks on the Edge}},\n  author = {Vignesh Sundaresha and Naresh Shanbhag},\n  year = {2024},\n  booktitle = {Neural Information Processing Systems (NeurIPS) Workshop on Machine Learning and Compression 2024},\n  url = {https://openreview.net/pdf?id=8rko2UqXdB}\n}",
      "rightsNotice": "Abstract reproduced from the linked arXiv version under <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0</a>. Wording unchanged."
    },
    {
      "title": "Geometric Programming Approach to Glitch Minimization via Gate Sizing",
      "url": "https://ieeexplore.ieee.org/document/9896135",
      "authors": "Karthikeyan Muthamizh Vithagan, <strong>Vignesh Sundaresha</strong>, Janakiraman Viraraghavan",
      "venue": "IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)",
      "year": 2023,
      "tags": [
        "vlsi"
      ],
      "abstract": "The problem of gate sizing to meet timing specification while minimizing functional power/area is well understood and is solved by the use of geometric programs (GPs). While these area minimization GP (AM-GP) formulations minimize functional power, they do not address the problem of glitches. Glitches are extraneous transitions caused by signal arrival time imbalance at the input nodes of logic gates. A gate sizing algorithm, Area-Glitch minimization GP (AGM-GP), is proposed to reduce glitches while constraining area and adhering to a timing specification. Glitch reduction is achieved through signal arrival time balancing posed as posynomials in a GP formulation. Prior art does not exploit the complete power of gate sizing when reducing glitches in an attempt to meet the timing specification. In particular, the proposed formulation allows both upsizing and downsizing without causing any timing violation, at the expense of a marginal increase in area. Traditional downsizing methods can be used to further reduce glitches over and above the AGM-GP solution. Simulation results on the ISCAS-85 benchmark circuits show an overall reduction of 20.4% glitch power and 9.5% total power which is respectively 13.8% and 3.9% better than just downsizing the AM-GP solution. This power reduction was achieved with an average area increase of 4.2%.",
      "abstractSource": "https://ieeexplore.ieee.org/document/9896135",
      "citationChicago": "Muthamizh Vithagan, Karthikeyan, Vignesh Sundaresha, and Janakiraman Viraraghavan. “Geometric Programming Approach to Glitch Minimization via Gate Sizing.” <em>IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems</em> 42, no. 6 (2023): 1988–2001. <a href=\"https://doi.org/10.1109/TCAD.2022.3207970\">https://doi.org/10.1109/TCAD.2022.3207970</a>.",
      "type": "journal",
      "bibtex": "@ARTICLE{9896135,\n  author={Muthamizh Vithagan, Karthikeyan and Sundaresha, Vignesh and Viraraghavan, Janakiraman},\n  journal={IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems}, \n  title={Geometric Programming Approach to Glitch Minimization via Gate Sizing}, \n  year={2023},\n  volume={42},\n  number={6},\n  pages={1988-2001},\n  doi={10.1109/TCAD.2022.3207970}}",
      "rightsNotice": "© 2022 IEEE. Personal use of this material is permitted. Permission from IEEE must be obtained for all other uses, in any current or future media, including reprinting/republishing this material for advertising or promotional purposes, creating new collective works, for resale or redistribution to servers or lists, or reuse of any copyrighted component of this work in other works."
    },
    {
      "title": "Localize to Binauralize: Audio Spatialization from Visual Sound Source Localization",
      "url": "https://openaccess.thecvf.com/content/ICCV2021/html/Rachavarapu_Localize_to_Binauralize_Audio_Spatialization_From_Visual_Sound_Source_Localization_ICCV_2021_paper.html",
      "authors": "Kranthi Kumar Rachavarapu, Aakanksha, <strong>Vignesh Sundaresha</strong>, A. N. Rajagopalan",
      "venue": "International Conference on Computer Vision (ICCV) 2021",
      "year": 2021,
      "tags": [
        "ml"
      ],
      "abstract": "Videos with binaural audios provide an immersive viewing experience by enabling 3D sound sensation. Recent works attempt to generate binaural audio in a multimodal learning framework using large quantities of videos with accompanying binaural audio. In contrast, we attempt a more challenging problem -- synthesizing binaural audios for a video with monaural audio in a weakly supervised setting and weakly semi-supervised setting. Our key idea is that any down-stream task that can be solved only using binaural audios can be used to provide proxy supervision for binaural audio generation, thereby reducing the reliance on explicit supervision. In this work, as a proxy-task for weak supervision, we use Sound Source Localization with only audio. We design a two-stage architecture called Localize-to-Binauralize Network (L2BNet). The first stage of L2BNet is a Stereo Generation (SG) network employed to generate two-stream audio from monaural audio using visual frame information as guidance. In the second stage, an Audio Localization (AL) network is designed to use the synthesized two-stream audio to localize sound sources in visual frames. The entire network is trained end-to-end so that the AL network provides necessary supervision for the SG network. We experimentally show that our weakly-supervised framework generates two-stream audio containing binaural cues. Through user study, we further validate that our proposed approach generates binaural-quality audio using as little as 10% of explicit binaural supervision data for the SG network.",
      "abstractSource": "https://openaccess.thecvf.com/content/ICCV2021/html/Rachavarapu_Localize_to_Binauralize_Audio_Spatialization_From_Visual_Sound_Source_Localization_ICCV_2021_paper.html",
      "citationChicago": "Rachavarapu, Kranthi Kumar, Aakanksha, Vignesh Sundaresha, and A. N. Rajagopalan. “Localize to Binauralize: Audio Spatialization From Visual Sound Source Localization.” In <em>Proceedings of the IEEE/CVF International Conference on Computer Vision</em>, 1930–39. 2021. <a href=\"https://openaccess.thecvf.com/content/ICCV2021/html/Rachavarapu_Localize_to_Binauralize_Audio_Spatialization_From_Visual_Sound_Source_Localization_ICCV_2021_paper.html\">https://openaccess.thecvf.com/content/ICCV2021/html/Rachavarapu_Localize_to_Binauralize_Audio_Spatialization_From_Visual_Sound_Source_Localization_ICCV_2021_paper.html</a>.",
      "type": "conference",
      "bibtex": "@InProceedings{Rachavarapu_2021_ICCV,\n    author    = {Rachavarapu, Kranthi Kumar and Aakanksha and Sundaresha, Vignesh and Rajagopalan, A. N.},\n    title     = {Localize to Binauralize: Audio Spatialization From Visual Sound Source Localization},\n    booktitle = {Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV)},\n    month     = {October},\n    year      = {2021},\n    pages     = {1930-1939}\n}",
      "rightsNotice": "© 2021 IEEE. Personal use of this material is permitted. Permission from IEEE must be obtained for all other uses, in any current or future media, including reprinting/republishing this material for advertising or promotional purposes, creating new collective works, for resale or redistribution to servers or lists, or reuse of any copyrighted component of this work in other works.",
      "codeUrl": "https://github.com/KranthiKumarR/Localize-to-Binauralize"
    }
  ]
};
